# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://blog.amen6.com"
uglyURLs = false

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

title = "MacKenzie's Blog"
author = "MacKenzie"
languageCode = "en-US"
enableRobotsTXT = false
enableEmoji = true

disableKinds = ["home"]
#ignoreErrors = ["error-disable-taxonomy"]

[params]
  description = "MacKenzie's Blog"
  favicon = "images/favicon.png"
  images = ["images/share2.png"]
  title = "MacKenzie's Blog"
  hideMadeWithLine = true
  dateFormat = "2006-01-02"
  contactEmail = ""

[deployment]

[[deployment.targets]]
name = "dev"
URL = "s3://blue-surf-7144?region=auto&endpoint=https://fly.storage.tigris.dev&profile=tigris"
